version: "3.7"

services:
  cra-app:
    build: cra-app
    command: yarn start
    environment:
      WDS_SOCKET_PORT: 13000
    ports:
      - 13000:3000
    volumes:
      - ./cra-app:/cra-app

  express-app:
    build: express-app
    command: yarn start
    environment:
      PORT: 8000
    ports:
      - 18000:8000
    volumes:
      - ./express-app:/express-app
